### ISSUE TITLE
Website does not compile anymore

### ISSUE THREAD

**Issue by florisvdh** [inbo/inbomd_examples#31]
E.g. see https://app.wercker.com/inbobmk/INBOmd/runs/build/5fae98a1237ec900082410db?step=5fae99295405fc0009d6bc6e, i.e. while testing PR inbo/INBOmd#68 (that PR itself should not be the cause). Maybe it has to do with recent updates in INBOtheme, cf. /inbo/INBOtheme#16.

Following error happens:

```
Quitting from lines 28-85 (vlaanderen_rapport.Rmd) 
Error in sub("color", "colour", x, fixed = TRUE) : 
  object 'vl.darkyellow' not found
Calls: local ... defaults -> rename_aes -> standardise_aes_names -> sub

Execution halted
Error: Failed to run 'render_book' in a new R session.
Execution halted
```

**Comment by ThierryO** [comment]
Yes, this is due to inbo/INBOtheme#16. The solution in mentioned in that issue.

**Comment by florisvdh** [comment]
I've been fixing the colour names but now this is the outcome ([link to build](https://app.wercker.com/inbobmk/inbomd_examples/runs/build/5faed5d7cce68900080cab4f?step=5faed6605405fc0009d7840f)).

```
Quitting from lines 545-551 (flanders_slides.Rmd) 
Error: `vlaanderen_palette()` has only 10 colours, you requested 16.
Reduce the number of factor levels.
In addition: Warning message:
In eval(ei, envir) :
  output file generated by other format will be overwritten

Execution halted
```

@ThierryO can you make the necessary changes in the affected example report(s)? It can be added to the upcoming PR where I (hopefully) solved all colour names already.
